#!/usr/bin/env bash
# remote-env.sh — generate the server-side .env with strong random secrets.
# Secrets are created ON the server (openssl) and never touch the git repo.
#
# Usage:
#   deploy/scripts/remote-env.sh            # create if missing
#   deploy/scripts/remote-env.sh --force    # regenerate (ROTATES all secrets!)
# Env overrides:
#   REMOTE_HOST  (default root@192.168.20.226)
#   REMOTE_DIR   (default /root/agent-platform)
#
# Generated secrets:
#   POSTGRES_PASSWORD  openssl rand -hex 16
#   JWT_SECRET         openssl rand -base64 32
#   ENCRYPTION_KEY     urlsafe-b64 of 32 random bytes (Fernet-compatible):
#                      openssl rand -base64 32 | tr '/+' '_-'
#                      (equivalent to Fernet.generate_key(); avoids needing
#                       python3+cryptography on the server)
# Non-secret defaults (COOKIE_SECURE=false for plain-HTTP phase; ALLOWED_ORIGINS
# derived from PORTAL_PORT — override with PORTAL_PORT=8180 remote-env.sh)
set -euo pipefail

REMOTE_HOST="${REMOTE_HOST:-root@192.168.20.226}"
REMOTE_DIR="${REMOTE_DIR:-/root/agent-platform}"
# 门户端口单一来源：PORTAL_PORT 与 ALLOWED_ORIGINS 均由它推导，消灭双处硬编码漂移
PORTAL_PORT="${PORTAL_PORT:-8080}"
FORCE="${1:-}"

if [ "$FORCE" != "--force" ]; then
  if ssh "$REMOTE_HOST" "test -f '$REMOTE_DIR/.env'"; then
    echo "!! $REMOTE_DIR/.env already exists on $REMOTE_HOST — keeping it."
    echo "   Re-run with --force to REGENERATE (rotates Postgres/JWT/encryption secrets;"
    echo "   rotating POSTGRES_PASSWORD without a volume wipe breaks DB auth; rotating"
    echo "   JWT_SECRET logs everyone out)."
    exit 0
  fi
fi

echo "==> generating $REMOTE_DIR/.env on $REMOTE_HOST (random secrets via openssl)"
ssh "$REMOTE_HOST" "mkdir -p '$REMOTE_DIR' && umask 077 && printf '%s\n' \
  '# agent-platform server env — generated by deploy/scripts/remote-env.sh' \
  'POSTGRES_DB=agent_platform' \
  'POSTGRES_USER=agent' \
  \"POSTGRES_PASSWORD=\$(openssl rand -hex 16)\" \
  \"JWT_SECRET=\$(openssl rand -base64 32 | tr -d '\n')\" \
  \"ENCRYPTION_KEY=\$(openssl rand -base64 32 | tr '/+' '_-')\" \
  'DIFY_BASE_URL=http://192.168.20.226' \
  "PORTAL_PORT=$PORTAL_PORT" \
  "ALLOWED_ORIGINS=http://192.168.20.226:$PORTAL_PORT" \
  'DEBUG=false' \
  '# 纯 HTTP 阶段必须 false，否则 Secure cookie 被浏览器拒收（登录即失效）；TLS 就绪后删除此行使缺省生效' \
  'COOKIE_SECURE=false' \
  > '$REMOTE_DIR/.env' && chmod 600 '$REMOTE_DIR/.env' && echo 'env written (mode 600)'"

echo "==> done. next: deploy/scripts/build-ship.sh then deploy/scripts/remote-up.sh"
